global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-monitoring'
    static_configs:
      - targets: ['localhost:8080']  # 根据你的API服务端口进行调整

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 